# Created with YamlCreate.ps1 v2.2.10 $debug=NVS1.CRLF.7-3-6.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: OtfriedCheong.IPE
PackageVersion: 7.2.28
PackageLocale: en-US
Publisher: Otfried Cheong
PublisherUrl: https://otfried.org/
PublisherSupportUrl: https://ipe.otfried.org/bugzilla.html
# PrivacyUrl:
Author: Otfried Cheong
PackageName: Ipe extensible drawing editor
PackageUrl: https://ipe.otfried.org/
License: GPL
LicenseUrl: https://www.gnu.org/copyleft/gpl.html
Copyright: Copyright © 1993–2023 Otfried Cheong
# CopyrightUrl:
ShortDescription: A drawing editor for creating figures in PDF format
Description: |2
  Ipe is a drawing editor for creating figures in PDF format. It supports making small figures for inclusion into LaTeX-documents as well as making multi-page PDF presentations.

  Ipe's main features are:
    - Entry of text as LaTeX source code. This makes it easy to enter mathematical expressions, and to reuse the LaTeX-macros of the main document. In the display text is displayed as it will appear in the figure.
    - Produces pure PDF, including the text. Ipe converts the LaTeX-source to PDF when the file is saved.
    - It is easy to align objects with respect to each other (for instance, to place a point on the intersection of two lines, or to draw a circle through three given points) using various snapping modes.
    - Users can provide ipelets (Ipe plug-ins) to add functionality to Ipe. This way, Ipe can be extended for each task at hand.
    - Ipe can be compiled for Unix, Windows, and OSX.
    - Ipe is written in standard C++ and Lua 5.4."
Moniker: ipe
# Tags:
# ReleaseNotes:
ReleaseNotesUrl: https://github.com/otfried/ipe/releases/tag/v7.2.28
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.5.0
